openapi: 3.0.0
info:
  title: Pet Store
  description: API for Pet Store Online Portal.
  version: 0.1.9
servers:
  - url: https://api.example.com/v1
    description: Main API server
  - url: https://staging-api.example.com
    description: Sandboxing server
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Retrieves all of Pet Store's users.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string